# # Silence everything except errors
# log4j.rootCategory=ERROR, console

# # Optional: Silence specific Spark internals
# log4j.logger.org.apache.spark=ERROR
# log4j.logger.org.sparkproject=ERROR
# log4j.logger.org.apache.hadoop=ERROR
# log4j.logger.org.apache.kafka=ERROR
# log4j.logger.org.eclipse.jetty=OFF
